services:
  backend:
    build: .
    container_name: ai_trade_backend
    restart: always
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8000:8000"
    volumes:
      # 将本地代码挂载到容器中，实现热重载
      - .:/app
    # extra_hosts 允许容器连接到宿主机上的服务。
    # 'host.docker.internal' 是一个特殊的DNS名称，它会解析为宿主机的IP地址。
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  db_data: